services:
  - type: web
    name: spaceinvaders
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
